<section x-data="{ dayOffModal: false }" @open-day-off-modal.window="dayOffModal = true" @close-day-off-modal.window="dayOffModal = false" class="rounded-[1.75rem] border border-[#171323]/8 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-white/6 sm:p-8">
    <div class="flex flex-wrap items-start justify-between gap-4"><div class="flex items-start gap-4"><span class="grid size-11 place-items-center rounded-2xl bg-amber-100 text-amber-700 dark:bg-amber-400/15 dark:text-amber-300"><i data-feather="sun" class="size-5"></i></span><div><p class="text-xs font-bold uppercase tracking-[0.2em] text-amber-600 dark:text-amber-300">Schedule exceptions</p><h2 class="mt-2 text-xl font-semibold">Days off</h2><p class="mt-1 text-sm text-[#171323]/50 dark:text-white/50">Workspace and individual closures are excluded from public booking.</p></div></div><button type="button" wire:click="startCreatingDayOff" class="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-[#171323] px-4 py-3 text-sm font-semibold text-white transition hover:bg-violet-700 dark:bg-violet-600 dark:hover:bg-violet-500"><i data-feather="plus" class="size-4"></i>Add day off</button></div>
    @if ($daysOff->isNotEmpty())
        <div class="mt-6 grid gap-2 border-t border-[#171323]/8 pt-6 sm:grid-cols-2 lg:grid-cols-3 dark:border-white/10">
            @foreach ($daysOff as $dayOff)
                <article wire:key="day-off-{{ $dayOff->id }}" class="flex min-w-0 items-center justify-between gap-3 rounded-xl border border-[#171323]/5 bg-[#f6f5f2] px-4 py-3 transition dark:border-white/8 dark:bg-[#211c31]"><div class="min-w-0"><p class="text-sm font-semibold">{{ $dayOff->local_date->format('D, M j, Y') }}</p><p class="mt-1 truncate text-xs text-[#171323]/45 dark:text-white/55">{{ $dayOff->reason ?: 'Day off' }} · {{ $dayOff->staff?->display_name ?? 'Everyone' }}</p></div><div class="flex shrink-0 items-center gap-1"><button type="button" wire:click="startEditingDayOff({{ $dayOff->id }})" class="cursor-pointer rounded-lg p-2 text-[#171323]/45 transition hover:bg-violet-100 hover:text-violet-700 dark:text-white/60 dark:hover:bg-violet-400/15 dark:hover:text-violet-200" aria-label="Edit day off"><i data-feather="edit-3" class="size-4"></i></button><button type="button" wire:click="removeDayOff({{ $dayOff->id }})" wire:confirm="Remove this day off? Booking will be available again if working hours allow it." wire:loading.attr="disabled" class="cursor-pointer rounded-lg p-2 text-[#171323]/45 transition hover:bg-rose-100 hover:text-rose-700 disabled:opacity-50 dark:text-white/60 dark:hover:bg-rose-400/10 dark:hover:text-rose-300" aria-label="Remove day off"><i data-feather="trash-2" class="size-4"></i></button></div></article>
            @endforeach
        </div>
    @else
        <div class="mt-6 rounded-2xl border border-dashed border-[#171323]/15 px-5 py-8 text-center dark:border-white/15"><i data-feather="calendar" class="mx-auto size-6 text-amber-600"></i><p class="mt-3 text-sm font-semibold">No upcoming days off</p><p class="mt-1 text-xs text-[#171323]/45 dark:text-white/45">Add a closure date and it will be excluded from availability.</p></div>
    @endif
    <div x-cloak x-show="dayOffModal" x-transition.opacity class="fixed inset-0 z-50 grid place-items-center bg-[#171323]/55 p-4 backdrop-blur-sm" @keydown.escape.window="dayOffModal = false" role="dialog" aria-modal="true" aria-labelledby="day-off-modal-title"><div @click.outside="dayOffModal = false" class="w-full max-w-lg rounded-[1.75rem] bg-white p-6 shadow-2xl dark:bg-[#1b1728] sm:p-8"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.2em] text-violet-600">Schedule exception</p><h3 id="day-off-modal-title" class="mt-2 text-2xl font-semibold dark:text-white">{{ $editingDayOffId ? 'Edit day off' : 'Add a day off' }}</h3><p class="mt-1 text-sm text-[#171323]/50 dark:text-white/50">Choose whether the closure applies to one person or everyone.</p></div><button type="button" wire:click="cancelEditingDayOff" @click="dayOffModal = false" class="rounded-xl p-2 text-[#171323]/50 hover:bg-[#f6f5f2] dark:text-white/50 dark:hover:bg-white/8" aria-label="Close"><i data-feather="x" class="size-5"></i></button></div>
        <form wire:submit="saveDayOff" class="mt-6 space-y-4">
            <div><span class="block text-sm font-medium dark:text-white">Date</span><div class="mt-2"><x-workspace.date-picker wire-model="dayOffDate" :value="$dayOffDate" :today="$today" /></div>@error('dayOffDate')<p class="mt-2 rounded-xl bg-rose-50 px-3 py-2 text-xs text-rose-700 dark:bg-rose-400/10 dark:text-rose-200">{{ $message }}</p>@enderror</div>
            <x-workspace.select label="Applies to" wire-model="dayOffStaffId" :value="$dayOffStaffId" :options="['' => 'Everyone'] + $staff->mapWithKeys(fn ($member) => [(string) $member->id => $member->display_name])->all()" />
            <div><label class="block text-sm font-medium dark:text-white">Reason <span class="font-normal text-[#171323]/40 dark:text-white/40">(optional)</span><input wire:model="dayOffReason" placeholder="Holiday or private event" class="mt-2 w-full rounded-xl border-[#171323]/10 bg-[#f6f5f2] px-4 py-3 dark:border-white/10 dark:bg-[#211c31] dark:text-white"></label>@error('dayOffReason')<p class="mt-2 rounded-xl bg-rose-50 px-3 py-2 text-xs text-rose-700 dark:bg-rose-400/10 dark:text-rose-200">{{ $message }}</p>@enderror</div>
            <div class="flex justify-end gap-2 border-t border-[#171323]/8 pt-4 dark:border-white/10"><button type="button" wire:click="cancelEditingDayOff" @click="dayOffModal = false" class="rounded-xl border border-[#171323]/10 px-4 py-3 text-sm font-semibold dark:border-white/10">Cancel</button><button type="submit" class="rounded-xl bg-[#171323] px-5 py-3 text-sm font-semibold text-white hover:bg-violet-700 disabled:opacity-50" wire:loading.attr="disabled">{{ $editingDayOffId ? 'Save changes' : 'Add day off' }}</button></div>
        </form>
    </div></div>
</section>
