<div class="space-y-8">
    <x-workspace.page-header eyebrow="{{ $tenant->name }}" title="Good morning, {{ explode(' ', auth()->user()->name)[0] }}" description="Here’s the rhythm of your workspace today." action-label="Open booking page" action-href="{{ route('business.show', $tenant) }}" />
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><x-workspace.metric-card label="Today’s appointments" :value="$stats['today']" detail="{{ \Carbon\CarbonImmutable::parse($today)->format('l, M j') }}" /><x-workspace.metric-card label="Active customers" :value="$stats['customers']" detail="People who trust your business" tone="emerald" /><x-workspace.metric-card label="Live services" :value="$stats['services']" detail="Ready to be booked" tone="amber" /><x-workspace.metric-card label="Team members" :value="$stats['team']" detail="Keeping the day moving" /></div>
    @if (! collect($setup)->every(fn ($complete) => $complete))
        <section class="rounded-[1.75rem] border border-[#171323]/8 bg-white p-6 text-[#171323] shadow-sm dark:border-white/10 dark:bg-[#171323] dark:text-white sm:p-8"><div class="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-[0.22em] text-violet-700 dark:text-violet-300">Workspace setup</p><h2 class="mt-2 text-2xl font-semibold">Make your booking page feel like you.</h2><p class="mt-2 max-w-xl text-sm leading-6 text-[#171323]/55 dark:text-white/55">A few details now create a smoother experience for every client later.</p></div><a wire:navigate href="{{ route('workspace.settings') }}" class="inline-flex items-center rounded-2xl bg-violet-700 px-4 py-3 text-sm font-semibold text-white transition hover:bg-violet-800 dark:bg-violet-300 dark:text-[#171323] dark:hover:bg-violet-200">Continue setup <i data-feather="arrow-right" class="ml-2 inline size-4"></i></a></div><div class="mt-7 grid gap-3 sm:grid-cols-4">@foreach ([['profile', 'Business profile'], ['services', 'Services'], ['team', 'Your team'], ['schedule', 'Availability']] as [$key, $label])<div class="flex items-center gap-3 rounded-2xl bg-[#f6f5f2] px-4 py-3 text-sm dark:bg-white/8"><span class="grid size-8 place-items-center rounded-xl {{ $setup[$key] ? 'bg-emerald-400 text-[#171323]' : 'bg-[#171323]/5 text-[#171323]/45 dark:bg-white/10 dark:text-white/45' }}"><i data-feather="{{ $setup[$key] ? 'check' : 'circle' }}" class="size-4"></i></span><span class="{{ $setup[$key] ? 'text-[#171323] dark:text-white' : 'text-[#171323]/55 dark:text-white/55' }}">{{ $label }}</span></div>@endforeach</div></section>
    @endif
    <div class="grid gap-6 xl:grid-cols-[1.4fr_0.6fr]">
        <section class="rounded-[1.75rem] border border-[#171323]/8 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-white/6 sm:p-8"><div class="flex items-center justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.2em] text-violet-600">Your day</p><h2 class="mt-2 text-xl font-semibold">Upcoming appointments</h2></div><a wire:navigate href="{{ route('workspace.calendar') }}" class="inline-flex items-center gap-1 text-sm font-semibold text-violet-600">Open calendar <i data-feather="arrow-right" class="size-4"></i></a></div><div class="mt-6 divide-y divide-[#171323]/8 dark:divide-white/10">@forelse ($todayAppointments as $appointment)<a wire:navigate href="{{ route('workspace.appointments.show', $appointment->id) }}" class="flex items-center gap-4 py-4 first:pt-0 last:pb-0"><span class="w-14 text-sm font-semibold text-[#171323]/45 dark:text-white/45">{{ $appointment->start_at->setTimezone($tenant->timezone)->format('H:i') }}</span><span class="grid size-10 place-items-center rounded-2xl bg-violet-100 text-violet-700"><i data-feather="calendar" class="size-5"></i></span><span class="min-w-0 flex-1"><span class="block truncate text-sm font-semibold">{{ $appointment->service_name ?: $appointment->service?->name }}</span><span class="mt-1 block truncate text-xs text-[#171323]/45 dark:text-white/45">{{ $appointment->customer?->name }} · {{ $appointment->staff?->display_name }}</span></span><x-workspace.status-badge :status="$appointment->status->value" /></a>@empty<x-workspace.empty-state title="Your day is open" message="New bookings will appear here as your clients choose a time." />@endforelse</div></section>
        <section class="rounded-[1.75rem] border border-[#171323]/8 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-white/6 sm:p-8"><p class="text-xs font-bold uppercase tracking-[0.2em] text-violet-600">Shortcuts</p><h2 class="mt-2 text-xl font-semibold">Move things forward</h2><div class="mt-6 space-y-3"><a wire:navigate href="{{ route('workspace.calendar') }}" class="flex items-center gap-3 rounded-2xl bg-[#f6f5f2] p-4 text-sm font-semibold transition hover:bg-violet-50 dark:bg-[#29243a] dark:hover:bg-[#342e43]"><span class="grid size-9 place-items-center rounded-xl bg-violet-100 text-violet-700"><i data-feather="calendar" class="size-4"></i></span>Plan the week <i data-feather="arrow-right" class="ml-auto size-4"></i></a><a wire:navigate href="{{ route('workspace.customers') }}" class="flex items-center gap-3 rounded-2xl bg-[#f6f5f2] p-4 text-sm font-semibold transition hover:bg-violet-50 dark:bg-[#29243a] dark:hover:bg-[#342e43]"><span class="grid size-9 place-items-center rounded-xl bg-emerald-100 text-emerald-700"><i data-feather="users" class="size-4"></i></span>Find a customer <i data-feather="arrow-right" class="ml-auto size-4"></i></a><a wire:navigate href="{{ route('workspace.settings') }}" class="flex items-center gap-3 rounded-2xl bg-[#f6f5f2] p-4 text-sm font-semibold transition hover:bg-violet-50 dark:bg-[#29243a] dark:hover:bg-[#342e43]"><span class="grid size-9 place-items-center rounded-xl bg-amber-100 text-amber-700"><i data-feather="settings" class="size-4"></i></span>Refine workspace <i data-feather="arrow-right" class="ml-auto size-4"></i></a></div></section>
    </div>
</div>
