<div class="space-y-8">
    <div class="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-[0.22em] text-violet-600">Insights</p><h1 class="mt-2 text-3xl font-semibold tracking-[-0.04em] text-[#171323] dark:text-white sm:text-4xl">Reports</h1><p class="mt-2 max-w-2xl text-sm leading-6 text-[#171323]/55 dark:text-white/55">Understand demand, outcomes, and the services shaping your month.</p></div><x-workspace.month-picker wire-model="month" :value="$month" /></div>

    <section class="rounded-[1.75rem] border border-[#171323]/8 bg-white p-6 text-[#171323] shadow-sm dark:border-white/10 dark:bg-[#171323] dark:text-white sm:p-8">
        <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.22em] text-violet-700 dark:text-violet-300">{{ $periodLabel }}</p><h2 class="mt-3 text-3xl font-semibold tracking-tight">Your month at a glance</h2></div><i data-feather="bar-chart-2" class="size-8 text-violet-700 dark:text-violet-300"></i></div>
        <div class="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
            <div class="rounded-2xl bg-[#f6f5f2] p-4 dark:bg-white/8"><p class="text-sm text-[#171323]/55 dark:text-white/55">Total appointments</p><p class="mt-2 text-3xl font-semibold">{{ $metrics['total'] }}</p></div>
            <div class="rounded-2xl bg-[#f6f5f2] p-4 dark:bg-white/8"><p class="text-sm text-[#171323]/55 dark:text-white/55">Confirmed</p><p class="mt-2 text-3xl font-semibold">{{ $metrics['confirmed'] }}</p></div>
            <div class="rounded-2xl bg-[#f6f5f2] p-4 dark:bg-white/8"><p class="text-sm text-[#171323]/55 dark:text-white/55">Completion rate</p><p class="mt-2 text-3xl font-semibold">{{ $metrics['completionRate'] }}%</p></div>
            <div class="rounded-2xl bg-[#f6f5f2] p-4 dark:bg-white/8"><p class="text-sm text-[#171323]/55 dark:text-white/55">Cancellation rate</p><p class="mt-2 text-3xl font-semibold">{{ $metrics['cancellationRate'] }}%</p></div><div class="rounded-2xl bg-[#f6f5f2] p-4 dark:bg-white/8"><p class="text-sm text-[#171323]/55 dark:text-white/55">Utilization</p><p class="mt-2 text-3xl font-semibold">{{ $metrics['utilizationRate'] }}%</p></div>
        </div>
    </section>

    <div class="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]">
        <section class="rounded-[1.75rem] border border-[#171323]/8 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-white/6 sm:p-8"><div class="flex items-center justify-between"><div><p class="text-xs font-bold uppercase tracking-[0.22em] text-violet-600">Demand</p><h2 class="mt-2 text-xl font-semibold">Appointments by service</h2></div><i data-feather="layers" class="size-5 text-violet-600"></i></div><div class="mt-6 space-y-4">@forelse ($serviceBreakdown as $service => $count)<div><div class="flex items-center justify-between text-sm"><span class="font-medium">{{ $service }}</span><span class="text-[#171323]/50 dark:text-white/50">{{ $count }}</span></div><div class="mt-2 h-2 overflow-hidden rounded-full bg-[#f0eff3] dark:bg-white/10"><div class="h-full rounded-full bg-violet-500" style="width: {{ max(8, (int) (($count / max(1, $metrics['total'])) * 100)) }}%"></div></div></div>@empty<x-workspace.empty-state title="No data for this month" message="Your service trends will appear after appointments are booked." />@endforelse</div></section>
        <section class="rounded-[1.75rem] border border-[#171323]/8 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-white/6 sm:p-8"><p class="text-xs font-bold uppercase tracking-[0.22em] text-amber-600">Outcomes</p><h2 class="mt-2 text-xl font-semibold">What happened</h2><div class="mt-6 space-y-3"><div class="flex items-center justify-between rounded-2xl bg-emerald-50 px-4 py-4 dark:bg-emerald-400/10"><span class="text-sm font-medium text-emerald-800 dark:text-emerald-300">Completed</span><strong class="text-xl text-emerald-700 dark:text-emerald-300">{{ $metrics['completed'] }}</strong></div><div class="flex items-center justify-between rounded-2xl bg-violet-50 px-4 py-4 dark:bg-violet-400/10"><span class="text-sm font-medium text-violet-800 dark:text-violet-300">Confirmed</span><strong class="text-xl text-violet-700 dark:text-violet-300">{{ $metrics['confirmed'] }}</strong></div><div class="flex items-center justify-between rounded-2xl bg-rose-50 px-4 py-4 dark:bg-rose-400/10"><span class="text-sm font-medium text-rose-800 dark:text-rose-300">Cancelled</span><strong class="text-xl text-rose-700 dark:text-rose-300">{{ $metrics['cancelled'] }}</strong></div><div class="flex items-center justify-between rounded-2xl bg-orange-50 px-4 py-4 dark:bg-orange-400/10"><span class="text-sm font-medium text-orange-800 dark:text-orange-300">No-shows</span><strong class="text-xl text-orange-700 dark:text-orange-300">{{ $metrics['noShows'] }}</strong></div></div></section>
    </div>
</div>
