<div x-data="{ serviceModal: false }" @open-service-modal.window="serviceModal = true" @close-service-modal.window="serviceModal = false" class="space-y-8">
    <x-workspace.page-header eyebrow="Offer" title="Services" description="Shape the experiences your clients can book." action-label="Open booking page" action-href="{{ route('business.show', auth()->user()->tenants()->wherePivot('is_active', true)->first()) }}" />

    @foreach (['service-created', 'service-updated'] as $flash)
        @if (session($flash))
            <span class="hidden" data-alertify-success="{{ session($flash) }}"></span>
        @endif
    @endforeach
    @if (session('service-error'))
        <span class="hidden" data-alertify-error="{{ session('service-error') }}"></span>
    @endif

    <section class="space-y-4">
        <div class="flex flex-wrap items-end justify-between gap-4">
            <div><p class="text-xs font-bold uppercase tracking-[0.2em] text-violet-600">Service catalog</p><h2 class="mt-2 text-2xl font-semibold tracking-tight">Bookable experiences</h2><p class="mt-1 text-sm text-[#171323]/50 dark:text-white/50">Manage what clients can book, how long it takes, and who provides it.</p></div>
            <div class="flex items-center gap-3"><span class="rounded-full bg-violet-100 px-3 py-1.5 text-xs font-semibold text-violet-700 dark:bg-violet-400/15 dark:text-violet-300">{{ $services->count() }} total</span><button type="button" wire:click="startCreatingService" class="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-[#171323] px-4 py-3 text-sm font-semibold text-white transition hover:bg-violet-700"><i data-feather="plus" class="size-4"></i>Add service</button></div>
        </div>

        <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
            @forelse ($services as $service)
                <article wire:key="service-card-{{ $service->id }}" class="flex min-h-full flex-col overflow-hidden rounded-[1.5rem] border border-[#171323]/8 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg dark:border-white/10 dark:bg-white/6">
                    <div class="flex-1 p-6">
                        <div class="flex items-start justify-between gap-3"><span class="grid size-11 place-items-center rounded-2xl bg-violet-100 text-violet-700 dark:bg-violet-400/15 dark:text-violet-300"><i data-feather="briefcase" class="size-5"></i></span><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $service->is_active ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-400/15 dark:text-emerald-300' : 'bg-slate-100 text-slate-500 dark:bg-white/10 dark:text-white/50' }}">{{ $service->is_active ? 'Live' : 'Paused' }}</span></div>
                        <h3 class="mt-5 text-lg font-semibold tracking-tight">{{ $service->name }}</h3><p class="mt-2 min-h-12 text-sm leading-6 text-[#171323]/50 dark:text-white/50">{{ $service->description ?: 'A focused appointment experience for your clients.' }}</p>
                        <div class="mt-5 flex flex-wrap gap-2"><span class="inline-flex items-center gap-1.5 rounded-lg bg-[#f6f5f2] px-3 py-2 text-xs font-semibold text-[#171323]/65 dark:bg-white/8 dark:text-white/65"><i data-feather="clock" class="size-3.5 text-violet-600 dark:text-violet-300"></i>{{ $service->duration_minutes }} min</span><span class="inline-flex items-center gap-1.5 rounded-lg bg-[#f6f5f2] px-3 py-2 text-xs font-semibold text-[#171323]/65 dark:bg-white/8 dark:text-white/65"><i data-feather="users" class="size-3.5 text-violet-600 dark:text-violet-300"></i>{{ $service->staff_count }} team member{{ $service->staff_count === 1 ? '' : 's' }}</span>@if ($service->buffer_minutes > 0)<span class="inline-flex items-center gap-1.5 rounded-lg bg-[#f6f5f2] px-3 py-2 text-xs font-semibold text-[#171323]/65 dark:bg-white/8 dark:text-white/65"><i data-feather="pause-circle" class="size-3.5 text-violet-600 dark:text-violet-300"></i>{{ $service->buffer_minutes }} min buffer</span>@endif</div>
                    </div>
                    <div class="flex flex-wrap gap-2 border-t border-[#171323]/8 bg-[#fbfaf9] p-4 dark:border-white/10 dark:bg-white/[0.025]">
                        <button type="button" wire:click="startEditingService({{ $service->id }})" class="inline-flex min-h-10 flex-1 cursor-pointer items-center justify-center gap-2 rounded-xl border border-[#171323]/10 bg-white px-3 py-2.5 text-xs font-semibold transition hover:border-violet-300 hover:text-violet-700 dark:border-white/10 dark:bg-white/5 dark:hover:text-violet-300"><i data-feather="edit-3" class="size-3.5"></i>Edit</button>
                        <button type="button" wire:click="toggleService({{ $service->id }})" class="inline-flex min-h-10 cursor-pointer items-center justify-center gap-2 rounded-xl border px-3 py-2.5 text-xs font-semibold transition {{ $service->is_active ? 'border-amber-200 bg-amber-50 text-amber-700 hover:bg-amber-100 dark:border-amber-400/20 dark:bg-amber-400/10 dark:text-amber-300 dark:hover:bg-amber-400/15' : 'border-emerald-200 bg-emerald-50 text-emerald-700 hover:bg-emerald-100 dark:border-emerald-400/20 dark:bg-emerald-400/10 dark:text-emerald-300 dark:hover:bg-emerald-400/15' }}"><i data-feather="{{ $service->is_active ? 'pause' : 'play' }}" class="size-3.5"></i>{{ $service->is_active ? 'Pause' : 'Activate' }}</button>
                        <button type="button" wire:click="removeService({{ $service->id }})" wire:confirm="Permanently remove this service? Services with appointment history must be paused instead so past bookings remain intact." class="inline-flex min-h-10 cursor-pointer items-center justify-center gap-2 rounded-xl border border-rose-200 bg-white px-3 py-2.5 text-xs font-semibold text-rose-700 transition hover:bg-rose-50 dark:border-rose-400/20 dark:bg-white/5 dark:text-rose-300 dark:hover:bg-rose-400/10"><i data-feather="trash-2" class="size-3.5"></i><span class="sr-only sm:not-sr-only">Remove</span></button>
                    </div>
                </article>
            @empty
                <div class="md:col-span-2 xl:col-span-3"><x-workspace.empty-state title="Create your first service" message="Add a bookable experience to get your service catalog started." /><div class="mt-4 text-center"><button type="button" wire:click="startCreatingService" class="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-[#171323] px-5 py-3 text-sm font-semibold text-white transition hover:bg-violet-700"><i data-feather="plus" class="size-4"></i>Create service</button></div></div>
            @endforelse
        </div>
    </section>

    <div x-cloak x-show="serviceModal" x-transition.opacity class="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-[#171323]/55 p-4 backdrop-blur-sm" @keydown.escape.window="serviceModal = false; $wire.cancelEditingService()" role="dialog" aria-modal="true" aria-labelledby="service-modal-title">
        <div @click.outside="serviceModal = false" class="my-auto w-full max-w-2xl rounded-[1.75rem] bg-white p-6 shadow-2xl dark:bg-[#1b1728] sm:p-8">
            <div class="flex items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.2em] text-violet-600">Service catalog</p><h3 id="service-modal-title" class="mt-2 text-2xl font-semibold dark:text-white">{{ $editingServiceId ? 'Edit service' : 'Create a service' }}</h3><p class="mt-1 text-sm text-[#171323]/50 dark:text-white/50">Set the details clients see when choosing an appointment.</p></div><button type="button" @click="serviceModal = false" wire:click="cancelEditingService" class="rounded-xl p-2 text-[#171323]/50 transition hover:bg-[#f6f5f2] dark:text-white/50 dark:hover:bg-white/8" aria-label="Close"><i data-feather="x" class="size-5"></i></button></div>
            <form wire:submit="{{ $editingServiceId ? 'updateService' : 'createService' }}" class="mt-6 space-y-5">
                <div><label class="block text-sm font-medium dark:text-white">Service name<input wire:model="serviceName" placeholder="e.g. Creative consultation" class="mt-2 w-full rounded-xl border border-[#171323]/10 bg-[#f6f5f2] px-4 py-3 dark:border-white/10 dark:bg-[#211c31] dark:text-white"></label>@error('serviceName')<p class="mt-2 rounded-xl bg-rose-50 px-3 py-2 text-xs text-rose-700 dark:bg-rose-400/10 dark:text-rose-200">{{ $message }}</p>@enderror</div>
                <div class="grid gap-4 sm:grid-cols-2"><div><label class="block text-sm font-medium dark:text-white">Duration <span class="font-normal text-[#171323]/45 dark:text-white/45">(minutes)</span><input wire:model="serviceDuration" type="number" min="5" max="1440" class="mt-2 w-full rounded-xl border border-[#171323]/10 bg-[#f6f5f2] px-4 py-3 dark:border-white/10 dark:bg-[#211c31] dark:text-white"></label>@error('serviceDuration')<p class="mt-2 rounded-xl bg-rose-50 px-3 py-2 text-xs text-rose-700 dark:bg-rose-400/10 dark:text-rose-200">{{ $message }}</p>@enderror</div><div><label class="block text-sm font-medium dark:text-white">Buffer <span class="font-normal text-[#171323]/45 dark:text-white/45">(minutes)</span><input wire:model="serviceBuffer" type="number" min="0" max="240" class="mt-2 w-full rounded-xl border border-[#171323]/10 bg-[#f6f5f2] px-4 py-3 dark:border-white/10 dark:bg-[#211c31] dark:text-white"></label>@error('serviceBuffer')<p class="mt-2 rounded-xl bg-rose-50 px-3 py-2 text-xs text-rose-700 dark:bg-rose-400/10 dark:text-rose-200">{{ $message }}</p>@enderror</div></div>
                <div><label class="block text-sm font-medium dark:text-white">Description <span class="font-normal text-[#171323]/45 dark:text-white/45">(optional)</span><textarea wire:model="serviceDescription" rows="4" placeholder="What should clients know before booking?" class="mt-2 w-full resize-y rounded-xl border border-[#171323]/10 bg-[#f6f5f2] px-4 py-3 dark:border-white/10 dark:bg-[#211c31] dark:text-white"></textarea></label>@error('serviceDescription')<p class="mt-2 rounded-xl bg-rose-50 px-3 py-2 text-xs text-rose-700 dark:bg-rose-400/10 dark:text-rose-200">{{ $message }}</p>@enderror</div>
                <div class="flex justify-end gap-2 border-t border-[#171323]/8 pt-5 dark:border-white/10"><button type="button" @click="serviceModal = false" wire:click="cancelEditingService" class="cursor-pointer rounded-xl border border-[#171323]/10 px-4 py-3 text-sm font-semibold transition hover:bg-[#f6f5f2] dark:border-white/10 dark:hover:bg-white/8">Cancel</button><button type="submit" wire:loading.attr="disabled" wire:target="{{ $editingServiceId ? 'updateService' : 'createService' }}" class="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-[#171323] px-5 py-3 text-sm font-semibold text-white transition hover:bg-violet-700 disabled:cursor-wait disabled:opacity-50"><i data-feather="{{ $editingServiceId ? 'save' : 'plus' }}" class="size-4"></i><span wire:loading.remove wire:target="{{ $editingServiceId ? 'updateService' : 'createService' }}">{{ $editingServiceId ? 'Save changes' : 'Add service' }}</span><span wire:loading wire:target="{{ $editingServiceId ? 'updateService' : 'createService' }}">Saving…</span></button></div>
            </form>
        </div>
    </div>
</div>
