<div class="space-y-8">
    <x-workspace.page-header eyebrow="Workspace" title="Settings" description="Keep your profile, booking rules, and availability in one calm place." />

    @if (session('profile-saved'))<span class="hidden" data-alertify-success="{{ session('profile-saved') }}"></span>@endif
    @if (session('token-created'))<span class="hidden" data-alertify-success="{{ session('token-created') }}"></span>@endif
    @if (session('token-revoked'))<span class="hidden" data-alertify-success="{{ session('token-revoked') }}"></span>@endif

    <div class="grid gap-6 xl:grid-cols-[1.35fr_0.65fr]">
        <section class="rounded-[1.75rem] border border-[#171323]/8 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-white/6 sm:p-8">
            <div class="flex items-start gap-4"><span class="grid size-12 place-items-center rounded-2xl bg-violet-100 text-violet-700"><i data-feather="settings" class="size-6"></i></span><div><h2 class="text-xl font-semibold">{{ $tenant->name }}</h2><p class="mt-1 text-sm text-[#171323]/50 dark:text-white/50">{{ $tenant->slug }} · {{ $tenant->timezone }}</p></div></div>
            <form wire:submit="updateTenantProfile" class="mt-8 grid gap-5 border-t border-[#171323]/8 pt-6 sm:grid-cols-2 dark:border-white/10">
                <div><label class="text-sm font-medium">Business name<input wire:model="tenantName" class="mt-2 w-full rounded-xl border border-[#171323]/10 bg-[#f6f5f2] px-4 py-3 transition focus:border-violet-500 focus:outline-none focus:ring-4 focus:ring-violet-500/10 dark:border-white/15 dark:bg-[#211c31] dark:text-white"></label>@error('tenantName')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
                <div><label class="text-sm font-medium">Public slug<input wire:model="tenantSlug" class="mt-2 w-full rounded-xl border border-[#171323]/10 bg-[#f6f5f2] px-4 py-3 transition focus:border-violet-500 focus:outline-none focus:ring-4 focus:ring-violet-500/10 dark:border-white/15 dark:bg-[#211c31] dark:text-white"></label>@error('tenantSlug')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
                <div><label class="text-sm font-medium">Timezone<select wire:model="tenantTimezone" class="mt-2 w-full rounded-xl border border-[#171323]/10 bg-[#f6f5f2] px-4 py-3 transition focus:border-violet-500 focus:outline-none focus:ring-4 focus:ring-violet-500/10 dark:border-white/15 dark:bg-[#211c31] dark:text-white">@foreach (DateTimeZone::listIdentifiers() as $timezone)<option value="{{ $timezone }}">{{ $timezone }}</option>@endforeach</select></label>@error('tenantTimezone')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
                <div><label class="text-sm font-medium">Booking horizon (days)<input wire:model="bookingHorizonDays" type="number" min="1" max="365" class="mt-2 w-full rounded-xl border border-[#171323]/10 bg-[#f6f5f2] px-4 py-3 transition focus:border-violet-500 focus:outline-none focus:ring-4 focus:ring-violet-500/10 dark:border-white/15 dark:bg-[#211c31] dark:text-white"></label>@error('bookingHorizonDays')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
                <div><label class="text-sm font-medium">Cancellation cutoff (hours)<input wire:model="cancellationCutoffHours" type="number" min="0" max="168" class="mt-2 w-full rounded-xl border border-[#171323]/10 bg-[#f6f5f2] px-4 py-3 transition focus:border-violet-500 focus:outline-none focus:ring-4 focus:ring-violet-500/10 dark:border-white/15 dark:bg-[#211c31] dark:text-white"></label><p class="mt-1 text-xs text-[#171323]/45 dark:text-white/45">Clients can cancel or reschedule until this many hours before the appointment.</p>@error('cancellationCutoffHours')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
                <div><label class="text-sm font-medium">Contact email<input wire:model="tenantEmail" type="email" class="mt-2 w-full rounded-xl border border-[#171323]/10 bg-[#f6f5f2] px-4 py-3 transition focus:border-violet-500 focus:outline-none focus:ring-4 focus:ring-violet-500/10 dark:border-white/15 dark:bg-[#211c31] dark:text-white"></label></div>
                <div><label class="text-sm font-medium">Contact phone<input wire:model="tenantPhone" class="mt-2 w-full rounded-xl border border-[#171323]/10 bg-[#f6f5f2] px-4 py-3 transition focus:border-violet-500 focus:outline-none focus:ring-4 focus:ring-violet-500/10 dark:border-white/15 dark:bg-[#211c31] dark:text-white"></label></div>
                <div class="sm:col-span-2"><button wire:loading.attr="disabled" class="rounded-xl bg-[#171323] px-5 py-3 text-sm font-semibold text-white transition hover:bg-violet-700 disabled:opacity-50">Save workspace profile</button></div>
            </form>
        </section>

        <div class="space-y-6">
            <section class="rounded-[1.75rem] border border-[#171323]/8 bg-white p-6 text-[#171323] shadow-sm dark:border-white/10 dark:bg-[#171323] dark:text-white sm:p-7"><p class="text-xs font-bold uppercase tracking-[0.22em] text-violet-700 dark:text-violet-300">Keep moving</p><h2 class="mt-3 text-xl font-semibold">Shape the experience</h2><p class="mt-2 text-sm leading-6 text-[#171323]/55 dark:text-white/55">Manage the parts of your booking flow from focused workspace pages.</p><div class="mt-6 space-y-2"><a wire:navigate href="{{ route('workspace.services') }}" class="flex items-center justify-between rounded-xl bg-[#f6f5f2] px-4 py-3 text-sm font-semibold transition hover:bg-violet-50 dark:bg-white/8 dark:hover:bg-white/15">Services <i data-feather="arrow-right" class="size-4"></i></a><a wire:navigate href="{{ route('workspace.team') }}" class="flex items-center justify-between rounded-xl bg-[#f6f5f2] px-4 py-3 text-sm font-semibold transition hover:bg-violet-50 dark:bg-white/8 dark:hover:bg-white/15">Team & availability <i data-feather="arrow-right" class="size-4"></i></a></div></section>
            <section class="rounded-[1.75rem] border border-[#171323]/8 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-white/6 sm:p-7"><p class="text-xs font-bold uppercase tracking-[0.22em] text-violet-600">Public presence</p><h2 class="mt-3 text-xl font-semibold">Your booking page</h2><p class="mt-2 text-sm leading-6 text-[#171323]/55 dark:text-white/55">Preview what clients see and share the link when you are ready.</p><a wire:navigate href="{{ route('business.show', $tenant) }}" class="mt-5 inline-flex rounded-xl border border-[#171323]/10 px-4 py-3 text-sm font-semibold hover:border-violet-300 hover:text-violet-700 dark:border-white/10">Preview booking page <i data-feather="arrow-up-right" class="ml-1 inline size-4"></i></a><div class="mt-6 border-t border-[#171323]/8 pt-5 dark:border-white/10"><p class="text-sm font-semibold">Embed your booking flow</p><p class="mt-1 text-xs leading-5 text-[#171323]/50 dark:text-white/50">Place this responsive booking card inside your website.</p><textarea readonly rows="3" class="mt-3 w-full rounded-xl border-[#171323]/10 bg-[#f6f5f2] px-3 py-3 font-mono text-[11px] text-[#171323]/70 dark:border-white/10 dark:bg-white/6 dark:text-white/70"><iframe src="{{ route('booking.embed', $tenant) }}" title="{{ $tenant->name }} booking" style="width:100%;min-height:720px;border:0;border-radius:24px" loading="lazy"></iframe></textarea><a href="{{ route('booking.embed', $tenant) }}" target="_blank" rel="noopener" class="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-violet-700 hover:text-violet-900 dark:text-violet-300">Open embed preview <i data-feather="external-link" class="size-4"></i></a></div></section>
        </div>
    </div>

<section class="rounded-[1.75rem] border border-[#171323]/8 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-white/6 sm:p-8">
    <div class="flex items-start gap-4">
        <span class="grid size-12 place-items-center rounded-2xl bg-amber-100 text-amber-700"><i data-feather="bell" class="size-6"></i></span>
        <div><h2 class="text-xl font-semibold">Notifications</h2><p class="mt-1 text-sm text-[#171323]/50 dark:text-white/50">Choose which operational updates your workspace receives.</p></div>
    </div>
    <div class="mt-6 grid gap-3 md:grid-cols-3">
        <label class="flex cursor-pointer items-start gap-3 rounded-2xl border border-[#171323]/8 p-4 dark:border-white/10"><input wire:model="notifyNewAppointments" type="checkbox" class="mt-1 rounded border-[#171323]/20 text-violet-600 focus:ring-violet-500"><span><span class="block text-sm font-semibold">New bookings</span><span class="mt-1 block text-xs leading-5 text-[#171323]/50 dark:text-white/50">Notify active team members when a booking request arrives.</span></span></label>
        <label class="flex cursor-pointer items-start gap-3 rounded-2xl border border-[#171323]/8 p-4 dark:border-white/10"><input wire:model="notifyAppointmentLifecycle" type="checkbox" class="mt-1 rounded border-[#171323]/20 text-violet-600 focus:ring-violet-500"><span><span class="block text-sm font-semibold">Appointment updates</span><span class="mt-1 block text-xs leading-5 text-[#171323]/50 dark:text-white/50">Keep active team members informed about status changes.</span></span></label>
        <label class="flex cursor-pointer items-start gap-3 rounded-2xl border border-[#171323]/8 p-4 dark:border-white/10"><input wire:model="remindersEnabled" type="checkbox" class="mt-1 rounded border-[#171323]/20 text-violet-600 focus:ring-violet-500"><span><span class="block text-sm font-semibold">Client reminders</span><span class="mt-1 block text-xs leading-5 text-[#171323]/50 dark:text-white/50">Send customers a reminder about confirmed appointments.</span></span></label>
    </div>
    <button wire:click="updateTenantProfile" wire:loading.attr="disabled" class="mt-5 rounded-xl bg-[#171323] px-5 py-3 text-sm font-semibold text-white transition hover:bg-violet-700 disabled:opacity-50">Save notification preferences</button>
</section>

<section class="grid gap-6 lg:grid-cols-2">
    <div class="rounded-[1.75rem] border border-[#171323]/8 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-white/6 sm:p-8">
        <div class="flex items-start gap-4"><span class="grid size-12 place-items-center rounded-2xl bg-sky-100 text-sky-700"><i data-feather="radio" class="size-6"></i></span><div><h2 class="text-xl font-semibold">Webhooks</h2><p class="mt-1 text-sm text-[#171323]/50 dark:text-white/50">Send signed appointment events to your systems.</p></div></div>
        <label class="mt-6 block text-sm font-medium">Endpoint URL<input wire:model="webhookUrl" type="url" placeholder="https://your-app.test/webhooks/appointly" class="mt-2 w-full rounded-xl border border-[#171323]/10 bg-[#f6f5f2] px-4 py-3 dark:border-white/15 dark:bg-[#211c31] dark:text-white"></label>
        @error('webhookUrl')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror
        <label class="mt-4 block text-sm font-medium">Signing secret<input wire:model="webhookSecret" type="text" class="mt-2 w-full rounded-xl border border-[#171323]/10 bg-[#f6f5f2] px-4 py-3 font-mono text-xs dark:border-white/15 dark:bg-[#211c31] dark:text-white"></label>
        <div class="mt-4 flex flex-wrap gap-2"><button wire:click="generateWebhookSecret" type="button" class="rounded-xl border border-[#171323]/10 px-4 py-2.5 text-sm font-semibold dark:border-white/10">Generate secret</button><button wire:click="updateTenantProfile" wire:loading.attr="disabled" type="button" class="rounded-xl bg-[#171323] px-4 py-2.5 text-sm font-semibold text-white hover:bg-violet-700">Save webhook</button></div>
    </div>
    <div class="rounded-[1.75rem] border border-[#171323]/8 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-white/6 sm:p-8">
        <div class="flex items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.22em] text-violet-600">Developer access</p><h2 class="mt-2 text-xl font-semibold">API keys</h2><p class="mt-1 text-sm text-[#171323]/50 dark:text-white/50">Create a tenant-scoped key for REST API clients.</p></div><i data-feather="key-round" class="size-6 text-violet-600"></i></div>
        @if ($newApiToken)<div class="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><p class="font-semibold">Copy this key now</p><p class="mt-2 break-all font-mono text-xs">{{ $newApiToken }}</p></div>@endif
        <button wire:click="createApiToken" type="button" class="mt-5 rounded-xl bg-[#171323] px-4 py-2.5 text-sm font-semibold text-white hover:bg-violet-700">Create API key</button>
        <div class="mt-6 space-y-2">@forelse ($apiTokens as $token)<div wire:key="api-token-{{ $token->id }}" class="flex items-center justify-between gap-3 rounded-xl border border-[#171323]/5 bg-[#f6f5f2] px-3 py-3 dark:border-white/8 dark:bg-[#29243a]"><div class="min-w-0"><p class="truncate text-xs font-semibold">{{ $token->name }}</p><p class="mt-1 text-[11px] text-[#171323]/45 dark:text-white/55">Created {{ $token->created_at?->diffForHumans() }}</p></div><button wire:click="revokeApiToken({{ $token->id }})" type="button" class="shrink-0 rounded-lg px-2.5 py-2 text-xs font-semibold text-rose-600 transition hover:bg-rose-50 dark:text-rose-300 dark:hover:bg-rose-400/10">Revoke</button></div>@empty<p class="mt-4 text-xs text-[#171323]/45 dark:text-white/45">No API keys have been created.</p>@endforelse</div>
    </div>
</section>
</div>
