<div x-data="{ staffModal: false, scheduleModal: false }"
    @open-staff-modal.window="staffModal = true" @close-staff-modal.window="staffModal = false"
    @open-schedule-modal.window="scheduleModal = true" @close-schedule-modal.window="scheduleModal = false"
    class="space-y-8">
    <x-workspace.page-header eyebrow="People" title="Team" description="Manage your people, services, and availability together." action-label="Workspace settings" action-href="{{ route('workspace.settings') }}" />

    @foreach (['staff-created', 'staff-updated', 'schedule-saved'] as $flash)
        @if (session($flash))
            <span class="hidden" data-alertify-success="{{ session($flash) }}"></span>
        @endif
    @endforeach
    @if (session('staff-error'))
        <span class="hidden" data-alertify-error="{{ session('staff-error') }}"></span>
    @endif

    <section class="space-y-4">
        <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.2em] text-emerald-600">People & availability</p><h2 class="mt-2 text-2xl font-semibold tracking-tight">Your team</h2><p class="mt-1 text-sm text-[#171323]/50 dark:text-white/50">Each person’s profile, services, and weekly hours are managed together.</p></div><div class="flex items-center gap-3"><span class="rounded-full bg-violet-100 px-3 py-1.5 text-xs font-semibold text-violet-700 dark:bg-violet-400/15 dark:text-violet-300">{{ $staff->count() }} total</span><button type="button" wire:click="startCreatingStaff" class="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-[#171323] px-4 py-3 text-sm font-semibold text-white transition hover:bg-violet-700"><i data-feather="user-plus" class="size-4"></i>Add member</button></div></div>

        <div class="grid gap-4 xl:grid-cols-2">
            @forelse ($staff as $member)
                <article wire:key="staff-card-{{ $member->id }}" class="overflow-hidden rounded-[1.5rem] border border-[#171323]/8 bg-white shadow-sm transition hover:shadow-md dark:border-white/10 dark:bg-white/6">
                    <div class="p-5 sm:p-6">
                        <div class="flex flex-wrap items-start justify-between gap-4">
                            <div class="flex min-w-0 items-center gap-4"><span class="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#171323] text-lg font-semibold text-white">{{ strtoupper(substr($member->display_name, 0, 1)) }}</span><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><h3 class="truncate font-semibold">{{ $member->display_name }}</h3><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $member->is_active ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-400/15 dark:text-emerald-300' : 'bg-slate-100 text-slate-500 dark:bg-white/10 dark:text-white/50' }}">{{ $member->is_active ? 'Active' : 'Paused' }}</span></div><p class="mt-1 text-xs text-[#171323]/45 dark:text-white/45">{{ $member->appointments_count }} appointments</p></div></div>
                            <div class="flex shrink-0 gap-2"><button type="button" wire:click="startEditingStaff({{ $member->id }})" class="inline-flex min-h-10 cursor-pointer items-center gap-2 rounded-xl border border-[#171323]/10 px-3 py-2 text-xs font-semibold transition hover:border-violet-300 hover:text-violet-700 dark:border-white/10 dark:hover:text-violet-300"><i data-feather="edit-3" class="size-3.5"></i>Edit</button><button type="button" wire:click="toggleStaff({{ $member->id }})" class="inline-flex min-h-10 cursor-pointer items-center gap-2 rounded-xl border px-3 py-2 text-xs font-semibold transition {{ $member->is_active ? 'border-amber-200 bg-amber-50 text-amber-700 hover:bg-amber-100 dark:border-amber-400/20 dark:bg-amber-400/10 dark:text-amber-300 dark:hover:bg-amber-400/15' : 'border-emerald-200 bg-emerald-50 text-emerald-700 hover:bg-emerald-100 dark:border-emerald-400/20 dark:bg-emerald-400/10 dark:text-emerald-300 dark:hover:bg-emerald-400/15' }}"><i data-feather="{{ $member->is_active ? 'pause' : 'play' }}" class="size-3.5"></i>{{ $member->is_active ? 'Pause' : 'Activate' }}</button><button type="button" wire:click="removeStaff({{ $member->id }})" wire:confirm="Permanently remove this teammate? Members with appointment history or assigned days off must be paused instead so existing records are preserved." class="inline-flex min-h-10 cursor-pointer items-center gap-2 rounded-xl border border-rose-200 px-3 py-2 text-xs font-semibold text-rose-700 transition hover:bg-rose-50 dark:border-rose-400/20 dark:text-rose-300 dark:hover:bg-rose-400/10"><i data-feather="trash-2" class="size-3.5"></i>Remove</button></div>
                        </div>
                        <p class="mt-4 text-sm leading-5 text-[#171323]/55 dark:text-white/55">{{ $member->description ?: 'Available for appointments.' }}</p>
                    </div>

                    <div class="border-t border-[#171323]/8 px-5 py-4 dark:border-white/10 sm:px-6">
                        <div class="flex items-center justify-between gap-3"><div><p class="text-xs font-semibold uppercase tracking-wider text-[#171323]/45 dark:text-white/45">Services</p><p class="mt-1 text-xs text-[#171323]/40 dark:text-white/40">Choose what this person can provide.</p></div></div>
                        <div class="mt-3 flex flex-wrap gap-2">
                            @forelse ($services as $service)
                                <button type="button" wire:key="staff-{{ $member->id }}-service-{{ $service->id }}" wire:click="toggleAssignment({{ $member->id }}, {{ $service->id }})" class="cursor-pointer rounded-full px-3 py-1.5 text-xs font-medium transition {{ $member->services->contains(fn ($assigned) => $assigned->id === $service->id && $assigned->pivot->is_active) ? 'bg-violet-600 text-white' : 'bg-[#f6f5f2] text-[#171323]/55 hover:bg-violet-100 dark:bg-white/8 dark:text-white/55 dark:hover:bg-violet-400/10' }}">{{ $service->name }}</button>
                            @empty
                                <p class="text-xs text-amber-600">Create a service before assigning work.</p>
                            @endforelse
                        </div>
                    </div>

                    <div class="border-t border-[#171323]/8 bg-[#fbfaf9] px-5 py-4 dark:border-white/10 dark:bg-white/[0.025] sm:px-6">
                        <div class="flex flex-wrap items-center justify-between gap-3"><div class="flex items-center gap-2"><span class="grid size-8 place-items-center rounded-lg bg-emerald-100 text-emerald-700 dark:bg-emerald-400/15 dark:text-emerald-300"><i data-feather="clock" class="size-4"></i></span><div><p class="text-sm font-semibold">Working hours</p><p class="text-xs text-[#171323]/45 dark:text-white/45">{{ $member->workingHours->count() }} scheduled day{{ $member->workingHours->count() === 1 ? '' : 's' }}</p></div></div><button type="button" wire:click="startCreatingWorkingHour({{ $member->id }})" class="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-[#171323] px-3 py-2 text-xs font-semibold text-white transition hover:bg-violet-700"><i data-feather="plus" class="size-3.5"></i>Add hours</button></div>
                        @if ($member->workingHours->isNotEmpty())
                            <div class="mt-4 grid gap-2 sm:grid-cols-2">
                                @foreach ($member->workingHours as $workingHour)
                                    <div wire:key="working-hour-{{ $workingHour->id }}" class="flex items-center justify-between gap-2 rounded-xl border border-[#171323]/6 bg-white px-3 py-2.5 dark:border-white/8 dark:bg-white/5"><div><p class="text-xs font-semibold">{{ ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'][$workingHour->weekday - 1] }}</p><p class="mt-1 text-xs text-[#171323]/50 dark:text-white/50">{{ substr($workingHour->start_local_time, 0, 5) }}–{{ substr($workingHour->end_local_time, 0, 5) }}</p></div><div class="flex items-center"><button type="button" wire:click="startEditingWorkingHour({{ $workingHour->id }})" class="cursor-pointer rounded-lg p-2 text-[#171323]/45 transition hover:bg-violet-100 hover:text-violet-700 dark:text-white/45 dark:hover:bg-violet-400/10 dark:hover:text-violet-300" aria-label="Edit working hours"><i data-feather="edit-3" class="size-4"></i></button><button type="button" wire:click="removeWorkingHour({{ $workingHour->id }})" wire:confirm="Remove these working hours? New appointments will no longer be offered during this time." class="cursor-pointer rounded-lg p-2 text-[#171323]/45 transition hover:bg-rose-100 hover:text-rose-700 dark:text-white/45 dark:hover:bg-rose-400/10 dark:hover:text-rose-300" aria-label="Remove working hours"><i data-feather="trash-2" class="size-4"></i></button></div></div>
                                @endforeach
                            </div>
                        @else
                            <div class="mt-4 rounded-xl border border-dashed border-[#171323]/12 px-4 py-5 text-center dark:border-white/12"><p class="text-xs font-medium text-[#171323]/50 dark:text-white/50">No weekly availability yet.</p><p class="mt-1 text-xs text-[#171323]/40 dark:text-white/40">Add hours so clients can book this team member.</p></div>
                        @endif
                    </div>
                </article>
            @empty
                <div class="xl:col-span-2"><x-workspace.empty-state title="Build your team" message="Add a team member above, then assign services and working hours here." /></div>
            @endforelse
        </div>
    </section>

    @include('livewire.workspace.day-off-manager')

    <div x-cloak x-show="staffModal" x-transition.opacity class="fixed inset-0 z-50 grid place-items-center bg-[#171323]/55 p-4 backdrop-blur-sm" @keydown.escape.window="staffModal = false; $wire.cancelEditingStaff()" role="dialog" aria-modal="true" aria-labelledby="staff-modal-title"><div @click.outside="staffModal = false" class="w-full max-w-lg rounded-[1.75rem] bg-white p-6 shadow-2xl dark:bg-[#1b1728] sm:p-8"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.2em] text-violet-600">Team profile</p><h3 id="staff-modal-title" class="mt-2 text-2xl font-semibold dark:text-white">{{ $editingStaffId ? 'Edit team member' : 'Add team member' }}</h3><p class="mt-1 text-sm text-[#171323]/50 dark:text-white/50">{{ $editingStaffId ? 'Update this person’s name and specialty.' : 'Add someone who can provide services and accept appointments.' }}</p></div><button type="button" @click="staffModal = false" wire:click="cancelEditingStaff" class="rounded-xl p-2 text-[#171323]/50 hover:bg-[#f6f5f2] dark:text-white/50 dark:hover:bg-white/8" aria-label="Close"><i data-feather="x" class="size-5"></i></button></div><form wire:submit="saveStaff" class="mt-6 space-y-4"><div><label class="block text-sm font-medium dark:text-white">Name<input wire:model="staffName" placeholder="e.g. Maya Chen" class="mt-2 w-full rounded-xl border-[#171323]/10 bg-[#f6f5f2] px-4 py-3 dark:border-white/10 dark:bg-[#211c31] dark:text-white"></label>@error('staffName')<p class="mt-2 rounded-xl bg-rose-50 px-3 py-2 text-xs text-rose-700 dark:bg-rose-400/10 dark:text-rose-200">{{ $message }}</p>@enderror</div><label class="block text-sm font-medium dark:text-white">Description <span class="font-normal text-[#171323]/40 dark:text-white/40">(optional)</span><textarea wire:model="staffDescription" rows="3" placeholder="Role or specialty" class="mt-2 w-full rounded-xl border-[#171323]/10 bg-[#f6f5f2] px-4 py-3 dark:border-white/10 dark:bg-[#211c31] dark:text-white"></textarea></label>@error('staffDescription')<p class="-mt-2 rounded-xl bg-rose-50 px-3 py-2 text-xs text-rose-700 dark:bg-rose-400/10 dark:text-rose-200">{{ $message }}</p>@enderror<div class="flex justify-end gap-2 border-t border-[#171323]/8 pt-4 dark:border-white/10"><button type="button" @click="staffModal = false" wire:click="cancelEditingStaff" class="rounded-xl border border-[#171323]/10 px-4 py-3 text-sm font-semibold dark:border-white/10">Cancel</button><button type="submit" wire:loading.attr="disabled" class="rounded-xl bg-[#171323] px-5 py-3 text-sm font-semibold text-white transition hover:bg-violet-700 disabled:opacity-50"><span wire:loading.remove wire:target="saveStaff">{{ $editingStaffId ? 'Save changes' : 'Add member' }}</span><span wire:loading wire:target="saveStaff">Saving…</span></button></div></form></div></div>

    <div x-cloak x-show="scheduleModal" x-transition.opacity class="fixed inset-0 z-50 grid place-items-center bg-[#171323]/55 p-4 backdrop-blur-sm" @keydown.escape.window="scheduleModal = false" role="dialog" aria-modal="true" aria-labelledby="schedule-modal-title"><div @click.outside="scheduleModal = false" class="w-full max-w-lg rounded-[1.75rem] bg-white p-6 shadow-2xl dark:bg-[#1b1728] sm:p-8"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.2em] text-emerald-600">Weekly availability</p><h3 id="schedule-modal-title" class="mt-2 text-2xl font-semibold dark:text-white">{{ $editingWorkingHourId ? 'Edit working hours' : 'Set working hours' }}</h3><p class="mt-1 text-sm text-[#171323]/50 dark:text-white/50">These hours determine which appointment times clients can book.</p></div><button type="button" @click="scheduleModal = false" wire:click="cancelEditingWorkingHour" class="rounded-xl p-2 text-[#171323]/50 hover:bg-[#f6f5f2] dark:text-white/50 dark:hover:bg-white/8" aria-label="Close"><i data-feather="x" class="size-5"></i></button></div><form wire:submit="saveWorkingHour" class="mt-6 space-y-4"><x-workspace.select label="Team member" wire-model="scheduleStaffId" :value="$scheduleStaffId" placeholder="Choose a team member" :options="$staff->mapWithKeys(fn ($member) => [(string) $member->id => $member->display_name])->all()" /><x-workspace.select label="Day of week" wire-model="scheduleWeekday" :value="$scheduleWeekday" :options="[1 => 'Monday', 2 => 'Tuesday', 3 => 'Wednesday', 4 => 'Thursday', 5 => 'Friday', 6 => 'Saturday', 7 => 'Sunday']" /><div class="grid gap-4 sm:grid-cols-2"><x-workspace.time-picker label="Starts at" wire-model="scheduleStart" :value="$scheduleStart" /><x-workspace.time-picker label="Ends at" wire-model="scheduleEnd" :value="$scheduleEnd" /></div><div class="flex justify-end gap-2 border-t border-[#171323]/8 pt-4 dark:border-white/10"><button type="button" @click="scheduleModal = false" wire:click="cancelEditingWorkingHour" class="rounded-xl border border-[#171323]/10 px-4 py-3 text-sm font-semibold dark:border-white/10">Cancel</button><button type="submit" wire:loading.attr="disabled" class="rounded-xl bg-[#171323] px-5 py-3 text-sm font-semibold text-white transition hover:bg-violet-700 disabled:opacity-50"><span wire:loading.remove wire:target="saveWorkingHour">{{ $editingWorkingHourId ? 'Save changes' : 'Save working hours' }}</span><span wire:loading wire:target="saveWorkingHour">Saving…</span></button></div></form></div></div>
</div>
